version: "3.9"

services:
  api:
    build: .
    container_name: image-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: node dist/index.js

  worker:
    build: .
    container_name: image-worker
    restart: always
    env_file:
      - .env
    command: node dist/worker/worker.js
